"""
patchframe.data.descriptor

Durable source descriptors for patchframe.

A source descriptor is the serialized identity plus reopen recipe for a source.
It is generated by source factories, make operators, or IO adapters, and is
used by ``SourceManager`` to open or reuse live ``DataSource`` instances.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Mapping


@dataclass(frozen=True, slots=True)
class SourceDescriptor:
    """Durable identity and reopen configuration for a data source."""

    source_type: str
    source_id: str
    open_config: Mapping[str, Any] = field(default_factory=dict)
    capabilities: Mapping[str, Any] = field(default_factory=dict)
